#!/usr/bin/env node
// Rebuilds the bundled plugin payload from the npm package.
//
// The plugin ships `dist/` (compiled) AND `node_modules` (prod deps) embedded,
// because Claude Code spawns the MCP server with `node` directly — not `npx` —
// to dodge the Windows spawn-ENOENT bug (#58510). Both folders ARE committed
// (web-eyes/.gitignore re-includes them): Claude Code copies the plugin into its
// cache and runs it there without building or installing, so anything not
// committed won't exist for the user. This script regenerates them from
// `package/`; commit the result.
//
// Steps: build the package -> copy dist -> install prod deps (no optional/dev)
// -> report sizes. Run from the repo root: `node scripts/prepare-plugin.mjs`.
//
// `--omit=optional` is mandatory: pdfjs-dist pulls @napi-rs/canvas (per-platform
// native binaries) as an optional dep the code never uses. Without it the plugin
// stops being portable. See Brain: estrutura-plugin.md.

import { execFileSync } from "node:child_process";
import { cpSync, rmSync, existsSync, statSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const packageDir = join(repoRoot, "package");
const pluginDir = join(repoRoot, "plugin");
const npm = process.platform === "win32" ? "npm.cmd" : "npm";

function run(cmd, args, cwd) {
  console.log(`\n$ ${cmd} ${args.join(" ")}  (in ${cwd})`);
  execFileSync(cmd, args, { cwd, stdio: "inherit", shell: process.platform === "win32" });
}

function dirSize(path) {
  if (!existsSync(path)) return 0;
  let total = 0;
  for (const entry of readdirSync(path, { withFileTypes: true })) {
    const full = join(path, entry.name);
    total += entry.isDirectory() ? dirSize(full) : statSync(full).size;
  }
  return total;
}

function mb(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

// 1. Build the package (tsc -> package/dist).
run(npm, ["run", "build"], packageDir);

// 2. Copy the freshly compiled dist into the plugin, replacing the old one.
const srcDist = join(packageDir, "dist");
const dstDist = join(pluginDir, "dist");
if (!existsSync(srcDist)) {
  console.error(`\n✗ ${srcDist} not found — build did not produce a dist/.`);
  process.exit(1);
}
rmSync(dstDist, { recursive: true, force: true });
cpSync(srcDist, dstDist, { recursive: true });
console.log(`\n✓ copied dist -> plugin/dist (${mb(dirSize(dstDist))})`);

// 3. Write a minimal package.json into the plugin holding only the package's
//    production dependencies, then install them. The plugin has no package.json
//    of its own (it's not an npm package — just a Claude Code plugin), so we
//    derive one from package/package.json to tell npm exactly what to fetch.
const pkg = JSON.parse(readFileSync(join(packageDir, "package.json"), "utf8"));
const pluginManifest = {
  name: "web-eyes-plugin-deps",
  version: pkg.version,
  private: true,
  description: "Bundled production deps for the web-eyes Claude Code plugin. Generated by prepare-plugin; do not edit by hand.",
  type: "module",
  dependencies: pkg.dependencies,
};
writeFileSync(join(pluginDir, "package.json"), JSON.stringify(pluginManifest, null, 2) + "\n");
console.log(`\n✓ wrote plugin/package.json (deps: ${Object.keys(pkg.dependencies).join(", ")})`);

// Install production deps, without optional or dev deps.
// `--omit=optional` keeps @napi-rs/canvas's native binaries out (unused).
run(npm, ["install", "--omit=optional", "--omit=dev"], pluginDir);

// 4. Report sizes so an oversized bundle is caught before release.
const nmSize = dirSize(join(pluginDir, "node_modules"));
const distSize = dirSize(dstDist);
console.log("\n── Plugin payload ──────────────────────");
console.log(`  dist/          ${mb(distSize)}`);
console.log(`  node_modules/  ${mb(nmSize)}`);
console.log(`  total          ${mb(distSize + nmSize)}`);
console.log("────────────────────────────────────────");
console.log("\n✓ Plugin prepared. dist/ and node_modules/ are COMMITTED (see web-eyes/.gitignore) —");
console.log("  Claude Code copies the plugin to its cache and runs it there, with no build");
console.log("  or install step, so review and commit these files for the plugin to work on a");
console.log("  fresh clone: `git status web-eyes/plugin`.");
